version: '3.8'

services:
  # Songs Microservice
  songs-api:
    build: .
    container_name: microservice-song-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb+srv://admin:admin123@cluster0.r2i9611.mongodb.net/polimusic_db?retryWrites=true&w=majority&appName=Cluster0
      - ALLOWED_ORIGINS=*
    networks:
      - polimusic-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  polimusic-network:
    driver: bridge