version: '3.8'

services:
      
  # Songs Microservice
  songs-api:
    build: .
    container_name: microservice-song-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb+srv://admin:admin123@cluster0.r2i9611.mongodb.net/polimusic_db?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - polimusic-network

volumes:
  mongodb_data:

networks:
  polimusic-network:
    driver: bridge